[project]
name = "canada"
authors = [
    {name = "Dmitriy Fedorov", email = "johndoe@example.com"},
]
description = "Make US redundant again"
requires-python = ">=3.7"
license = {text = "Apache 2.0"}
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["."]
