name: mypy
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - run: pip install -r requirements.txt
    - run: pip install .
    - run: pip install mypy==1.8.0
    - run: mypy canada
