name: tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - run: pip install .[tests]
    - run: pip install ytsaurus-client
    - run: docker compose -f "tests/docker-compose.yml" up -d
    - run: echo "node-id=$(yt --proxy http://localhost:58080 create --path //canada_tests --type map_node)\n" | tr -d '\n' >> $GITHUB_OUTPUT
      id: create_yt_node
    - run: pytest tests
      env:
        YT_HOST: "http://localhost:58080"
        ROOT_COLLECTION_NODE_ID: ${{ steps.create_yt_node.outputs.node-id }}
